// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "d_sigmoid.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic d_sigmoid::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic d_sigmoid::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<13> d_sigmoid::ap_ST_fsm_state1 = "1";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state2 = "10";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state3 = "100";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state4 = "1000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state5 = "10000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state6 = "100000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state7 = "1000000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state8 = "10000000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state9 = "100000000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state10 = "1000000000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state11 = "10000000000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state12 = "100000000000";
const sc_lv<13> d_sigmoid::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<32> d_sigmoid::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> d_sigmoid::ap_const_lv32_1 = "1";
const sc_lv<32> d_sigmoid::ap_const_lv32_2 = "10";
const sc_lv<32> d_sigmoid::ap_const_lv32_6 = "110";
const sc_lv<32> d_sigmoid::ap_const_lv32_B = "1011";
const sc_lv<4> d_sigmoid::ap_const_lv4_0 = "0000";
const sc_lv<32> d_sigmoid::ap_const_lv32_C = "1100";
const sc_lv<64> d_sigmoid::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<32> d_sigmoid::ap_const_lv32_7 = "111";
const sc_lv<4> d_sigmoid::ap_const_lv4_8 = "1000";
const sc_lv<4> d_sigmoid::ap_const_lv4_1 = "1";
const sc_lv<1> d_sigmoid::ap_const_lv1_1 = "1";
const sc_lv<3> d_sigmoid::ap_const_lv3_0 = "000";
const sc_lv<64> d_sigmoid::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const bool d_sigmoid::ap_const_boolean_1 = true;

d_sigmoid::d_sigmoid(sc_module_name name) : sc_module(name), mVcdFile(0) {
    d_sigmoid_dsub_64bkb_U1 = new d_sigmoid_dsub_64bkb<1,5,64,64,64>("d_sigmoid_dsub_64bkb_U1");
    d_sigmoid_dsub_64bkb_U1->clk(ap_clk);
    d_sigmoid_dsub_64bkb_U1->reset(ap_rst);
    d_sigmoid_dsub_64bkb_U1->din0(ap_var_for_const0);
    d_sigmoid_dsub_64bkb_U1->din1(layer_output_q0);
    d_sigmoid_dsub_64bkb_U1->ce(ap_var_for_const1);
    d_sigmoid_dsub_64bkb_U1->dout(grp_fu_68_p2);
    d_sigmoid_dmul_64cud_U2 = new d_sigmoid_dmul_64cud<1,5,64,64,64>("d_sigmoid_dmul_64cud_U2");
    d_sigmoid_dmul_64cud_U2->clk(ap_clk);
    d_sigmoid_dmul_64cud_U2->reset(ap_rst);
    d_sigmoid_dmul_64cud_U2->din0(layer_output_load_reg_113);
    d_sigmoid_dmul_64cud_U2->din1(tmp_reg_119);
    d_sigmoid_dmul_64cud_U2->ce(ap_var_for_const1);
    d_sigmoid_dmul_64cud_U2->dout(grp_fu_74_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln11_fu_78_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln11_fu_78_p2 );

    SC_METHOD(thread_i_fu_84_p2);
    sensitive << ( i_0_reg_56 );

    SC_METHOD(thread_icmp_ln11_fu_78_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_56 );

    SC_METHOD(thread_layer_derivative_address0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( zext_ln12_1_fu_95_p1 );

    SC_METHOD(thread_layer_derivative_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_layer_derivative_d0);
    sensitive << ( tmp_1_reg_124 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_layer_derivative_we0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_layer_input_address0);

    SC_METHOD(thread_layer_input_address1);

    SC_METHOD(thread_layer_input_ce0);

    SC_METHOD(thread_layer_input_ce1);

    SC_METHOD(thread_layer_input_d0);

    SC_METHOD(thread_layer_input_d1);

    SC_METHOD(thread_layer_input_we0);

    SC_METHOD(thread_layer_input_we1);

    SC_METHOD(thread_layer_output_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln12_fu_90_p1 );

    SC_METHOD(thread_layer_output_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zext_ln12_1_fu_95_p1);
    sensitive << ( i_0_reg_56 );

    SC_METHOD(thread_zext_ln12_fu_90_p1);
    sensitive << ( i_fu_84_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln11_fu_78_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "d_sigmoid_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, layer_input_address0, "(port)layer_input_address0");
    sc_trace(mVcdFile, layer_input_ce0, "(port)layer_input_ce0");
    sc_trace(mVcdFile, layer_input_we0, "(port)layer_input_we0");
    sc_trace(mVcdFile, layer_input_d0, "(port)layer_input_d0");
    sc_trace(mVcdFile, layer_input_q0, "(port)layer_input_q0");
    sc_trace(mVcdFile, layer_input_address1, "(port)layer_input_address1");
    sc_trace(mVcdFile, layer_input_ce1, "(port)layer_input_ce1");
    sc_trace(mVcdFile, layer_input_we1, "(port)layer_input_we1");
    sc_trace(mVcdFile, layer_input_d1, "(port)layer_input_d1");
    sc_trace(mVcdFile, layer_input_q1, "(port)layer_input_q1");
    sc_trace(mVcdFile, layer_output_address0, "(port)layer_output_address0");
    sc_trace(mVcdFile, layer_output_ce0, "(port)layer_output_ce0");
    sc_trace(mVcdFile, layer_output_q0, "(port)layer_output_q0");
    sc_trace(mVcdFile, layer_derivative_address0, "(port)layer_derivative_address0");
    sc_trace(mVcdFile, layer_derivative_ce0, "(port)layer_derivative_ce0");
    sc_trace(mVcdFile, layer_derivative_we0, "(port)layer_derivative_we0");
    sc_trace(mVcdFile, layer_derivative_d0, "(port)layer_derivative_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_84_p2, "i_fu_84_p2");
    sc_trace(mVcdFile, i_reg_103, "i_reg_103");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln11_fu_78_p2, "icmp_ln11_fu_78_p2");
    sc_trace(mVcdFile, layer_output_load_reg_113, "layer_output_load_reg_113");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_fu_68_p2, "grp_fu_68_p2");
    sc_trace(mVcdFile, tmp_reg_119, "tmp_reg_119");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_74_p2, "grp_fu_74_p2");
    sc_trace(mVcdFile, tmp_1_reg_124, "tmp_1_reg_124");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, i_0_reg_56, "i_0_reg_56");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, zext_ln12_fu_90_p1, "zext_ln12_fu_90_p1");
    sc_trace(mVcdFile, zext_ln12_1_fu_95_p1, "zext_ln12_1_fu_95_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("d_sigmoid.hdltvin.dat");
    mHdltvoutHandle.open("d_sigmoid.hdltvout.dat");
}

d_sigmoid::~d_sigmoid() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete d_sigmoid_dsub_64bkb_U1;
    delete d_sigmoid_dmul_64cud_U2;
}

void d_sigmoid::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_1;
}

void d_sigmoid::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv64_3FF0000000000000;
}

void d_sigmoid::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        i_0_reg_56 = i_reg_103.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_56 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_103 = i_fu_84_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        layer_output_load_reg_113 = layer_output_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_1_reg_124 = grp_fu_74_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_reg_119 = grp_fu_68_p2.read();
    }
}

void d_sigmoid::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void d_sigmoid::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void d_sigmoid::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void d_sigmoid::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void d_sigmoid::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void d_sigmoid::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void d_sigmoid::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void d_sigmoid::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln11_fu_78_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void d_sigmoid::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void d_sigmoid::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln11_fu_78_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void d_sigmoid::thread_i_fu_84_p2() {
    i_fu_84_p2 = (!i_0_reg_56.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_56.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void d_sigmoid::thread_icmp_ln11_fu_78_p2() {
    icmp_ln11_fu_78_p2 = (!i_0_reg_56.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_56.read() == ap_const_lv4_8);
}

void d_sigmoid::thread_layer_derivative_address0() {
    layer_derivative_address0 =  (sc_lv<3>) (zext_ln12_1_fu_95_p1.read());
}

void d_sigmoid::thread_layer_derivative_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        layer_derivative_ce0 = ap_const_logic_1;
    } else {
        layer_derivative_ce0 = ap_const_logic_0;
    }
}

void d_sigmoid::thread_layer_derivative_d0() {
    layer_derivative_d0 = tmp_1_reg_124.read();
}

void d_sigmoid::thread_layer_derivative_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        layer_derivative_we0 = ap_const_logic_1;
    } else {
        layer_derivative_we0 = ap_const_logic_0;
    }
}

void d_sigmoid::thread_layer_input_address0() {
    layer_input_address0 = ap_const_lv3_0;
}

void d_sigmoid::thread_layer_input_address1() {
    layer_input_address1 = ap_const_lv3_0;
}

void d_sigmoid::thread_layer_input_ce0() {
    layer_input_ce0 = ap_const_logic_0;
}

void d_sigmoid::thread_layer_input_ce1() {
    layer_input_ce1 = ap_const_logic_0;
}

void d_sigmoid::thread_layer_input_d0() {
    layer_input_d0 = ap_const_lv64_0;
}

void d_sigmoid::thread_layer_input_d1() {
    layer_input_d1 = ap_const_lv64_0;
}

void d_sigmoid::thread_layer_input_we0() {
    layer_input_we0 = ap_const_logic_0;
}

void d_sigmoid::thread_layer_input_we1() {
    layer_input_we1 = ap_const_logic_0;
}

void d_sigmoid::thread_layer_output_address0() {
    layer_output_address0 =  (sc_lv<3>) (zext_ln12_fu_90_p1.read());
}

void d_sigmoid::thread_layer_output_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        layer_output_ce0 = ap_const_logic_1;
    } else {
        layer_output_ce0 = ap_const_logic_0;
    }
}

void d_sigmoid::thread_zext_ln12_1_fu_95_p1() {
    zext_ln12_1_fu_95_p1 = esl_zext<64,4>(i_0_reg_56.read());
}

void d_sigmoid::thread_zext_ln12_fu_90_p1() {
    zext_ln12_fu_90_p1 = esl_zext<64,4>(i_fu_84_p2.read());
}

void d_sigmoid::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln11_fu_78_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXX";
            break;
    }
}

void d_sigmoid::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_input_address0\" :  \"" << layer_input_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_input_ce0\" :  \"" << layer_input_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_input_we0\" :  \"" << layer_input_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_input_d0\" :  \"" << layer_input_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer_input_q0\" :  \"" << layer_input_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_input_address1\" :  \"" << layer_input_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_input_ce1\" :  \"" << layer_input_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_input_we1\" :  \"" << layer_input_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_input_d1\" :  \"" << layer_input_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer_input_q1\" :  \"" << layer_input_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_output_address0\" :  \"" << layer_output_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_output_ce0\" :  \"" << layer_output_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"layer_output_q0\" :  \"" << layer_output_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_derivative_address0\" :  \"" << layer_derivative_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_derivative_ce0\" :  \"" << layer_derivative_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_derivative_we0\" :  \"" << layer_derivative_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"layer_derivative_d0\" :  \"" << layer_derivative_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

